# Generated by Django 4.2.27 on 2026-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
