# Generated by Django 4.2.27 on 2026-03-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
